name: Verify Docs Quality
on:
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/verify_docs-quality.yml'
      - '**.md'

jobs:
  check-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install vale
        run: |
          gh release download --repo errata-ai/vale -p 'vale_*_Linux_64-bit.tar.gz' -D /tmp
          tar -xzf /tmp/vale_*_Linux_64-bit.tar.gz -C /usr/local/bin vale
          vale --version
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Get changed files
        run: |
          gh api "repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" \
            --paginate -q '.[] | select(.status != "removed") | .filename' > /tmp/pr-files.txt
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Documentation quality check
        run: node scripts/check-docs-quality.js --ci /tmp/pr-files.txt
